=== msknapp/JModelBuilder/src/test/ModelDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project (defaults?,package*,interface*,enum*,class*)>
<!ELEMENT defaults EMPTY >
<!ELEMENT package (package*,interface*,enum*,class*)>
<!ELEMENT class (implements*,field*,requiredMethod*,interface*,enum*,class*)>
<!ELEMENT interface (field*,requiredMethod*)>
<!ELEMENT enum (field*,requiredMethod*,enumInstance*)>
<!ELEMENT requiredMethod (type?,argument*)>
<!ELEMENT field (type?)>
<!ELEMENT type (type*) >
<!ELEMENT argument (type?) >
<!ELEMENT implements EMPTY>
<!ELEMENT enumInstance EMPTY>
<!ATTLIST project id CDATA "" >
<!ATTLIST project name CDATA #REQUIRED>
<!ATTLIST project programmingLanguage CDATA #REQUIRED>
<!ATTLIST defaults id CDATA "" >
<!ATTLIST defaults author CDATA "" >
<!ATTLIST defaults includeIncrementMethod (true|false) "true" >
<!ATTLIST defaults includeDecrementMethod (true|false) "true" >
<!ATTLIST defaults includeAddMethod (true|false) "true" >
<!ATTLIST defaults includeRemoveMethod (true|false) "true" >
<!ATTLIST defaults includeJavadocs (true|false) "true" >
<!ATTLIST package id CDATA "" >
<!ATTLIST package name CDATA #REQUIRED>
<!ATTLIST class id CDATA "" >
<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST class inherits CDATA "Object">
<!ATTLIST class abstract (true|false) "false" >
<!ATTLIST class comparable (true|false) "true">
<!ATTLIST class serializable (true|false) "true">
<!ATTLIST class final (true|false) "false">
<!ATTLIST class static (true|false) "false">
<!ATTLIST interface id CDATA "" >
<!ATTLIST interface name CDATA #REQUIRED >
<!ATTLIST enum id CDATA "" >
<!ATTLIST enum name CDATA #REQUIRED >
<!ATTLIST implements id CDATA "" >
<!ATTLIST implements name CDATA #REQUIRED >
<!ATTLIST requiredMethod id CDATA "" >
<!ATTLIST requiredMethod name CDATA #REQUIRED >
<!ATTLIST requiredMethod returnType CDATA "">
<!ATTLIST requiredMethod visibility (public|protected|packageprivate|private) "public">
<!ATTLIST requiredMethod static (true|false) "false" >
<!ATTLIST requiredMethod synchronized (true|false) "false" >
<!ATTLIST requiredMethod abstract (true|false) "false" >
<!ATTLIST requiredMethod overrides (true|false) "false" >
<!ATTLIST requiredMethod modifiesClass (true|false) "true" >
<!ATTLIST requiredMethod final (true|false) "false">
<!ATTLIST field id CDATA "" >
<!ATTLIST field type CDATA "" >
<!ATTLIST field visibility (public|protected|packageprivate|private) "private">
<!ATTLIST field gettable (true|false) "true" >
<!ATTLIST field settable (true|false) "true" >
<!ATTLIST field addable (true|false) "true" >
<!ATTLIST field removable (true|false) "true">
<!ATTLIST field incrementable (true|false) "true">
<!ATTLIST field decrementable (true|false) "true">
<!ATTLIST field serializable (true|false) "true">
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field unique (true|false) "true">
<!ATTLIST field compareOrder (-1|0|1|2|3|4|5|6|7|8|9|10|11|12) "-1">
<!ATTLIST field static (true|false) "false" >
<!ATTLIST field synchronized (true|false) "false" >
<!ATTLIST field abstract (true|false) "false" >
<!ATTLIST field overrides (true|false) "false" >
<!ATTLIST field final (true|false) "false">
<!ATTLIST field defaultValue CDATA "null">
<!ATTLIST argument id CDATA "" >
<!ATTLIST argument name CDATA "" >
<!ATTLIST argument type CDATA "" >
<!ATTLIST argument final (true|false) "false">
<!ATTLIST type id CDATA "" >
<!ATTLIST type name CDATA "" >
<!ATTLIST type arrayDimensions (0|1|2|3|4) "0" >
<!ATTLIST enumInstance id CDATA "" >
<!ATTLIST enumInstance name CDATA "" >

=== msknapp/JModelBuilder/src/test/TestModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "ModelDefinition.dtd">
<project name="words">
	<defaults>
	
	</defaults>
	<package name="com">
		<package name="knapptech">
			<package name="wordmodel">
				<class name="Document">
					<field name="paragraphs" type="java.util.List&lt;com.knapptech.wordmodel.Paragraph&gt;" />
					<field name="author" type="com.knapptech.user.User" />
					<field name="creationDate" type="java.util.Calendar" />
					<field name="lastUpdate" type="java.util.Calendar" />
				</class>
				<class name="Paragraph">
					<field name="sentences" type="java.util.List&lt;com.knapptech.wordmodel.Sentence&gt;" />
					<field name="document" type="com.knapptech.wordmodel.Document" />
					
				</class>
				<class name="Sentence">
					<field name="words" type="java.util.List&lt;com.knapptech.wordmodel.SentencePart&gt;" />
					<field name="paragraph" type="com.knapptech.wordmodel.Paragraph" />
				</class>
				<class name="SentencePart">
					<field name="text" type="String" />
					<field name="val" type="int" />
					<field name="sentence" type="com.knapptech.wordmodel.Sentence" />
					
				</class> 
			</package>
			<package name="user">
				<class name="User">
					<field name="firstName" type="String" />
					<field name="lastName" type="String" />
					<field name="password" type="char[]" />
					<field name="loginName" type="String" />
				</class>
				
			</package>
		</package>
	</package>
</project>

=== msknapp/JModelBuilder/src/test/DeathMatchSite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "ModelDefinition.dtd">
<project name="DeathMatch">
	<defaults>
	
	</defaults>
	<package name="com">
		<package name="knapptech">
			<package name="autogen">
				<package name="deathmatch">
					<class name="Player" >
						<field name="name" type="String" compareOrder="0"/>
						<field name="inventory" type="com.knapptech.autogen.deathmatch.PlayerInventory" />
						<field name="health" type="byte" />
						<field name="armor" type="byte" />
						<field name="transform" type="com.knapptech.autogen.deathmatch.Transform" />
					</class>
					<class name="Transform" >
						<field name="position" type="com.knapptech.autogen.shape.Vector3"></field>
						<field name="rotation" type="com.knapptech.autogen.shape.Vector4"></field>
						<field name="localScale" type="com.knapptech.autogen.shape.Vector3"></field>
					</class>
					<class name="PlayerInventory">
						<field name="guns" type="java.util.List&lt;com.knapptech.autogen.deathmatch.Gun&gt;" />
					</class>
					<class name="Gun">
						<field name="type" type="com.knapptech.autogen.deathmatch.GunType" compareOrder="0"/>
						<field name="ammo" type="double" />
					</class>
					<class name="GunType">
						<field name="reloadtime" type="double" />
						<field name="name" type="String" compareOrder="0"/>
						<field name="damage" type="byte" />
					</class>
					
					<class name="Ammo">
						<field name="gunType" type="com.knapptech.autogen.deathmatch.GunType" />
					
					</class>
					<class name="Level" >
					
					
					</class>
				</package>
				<package name="shape">
					<class name="Vector2">
						<field name="x" type="float"></field>
						<field name="y" type="float"></field>
					</class>
					<class name="Vector3" inherits="com.knapptech.autogen.shape.Vector2">
						<field name="z" type="float"></field>
					</class>
					<class name="Vector4" inherits="com.knapptech.autogen.shape.Vector3">
						<field name="w" type="float"></field>
					</class>
					<class name="Ray">
						<field name="startPoint" type="com.knapptech.autogen.shape.Vector3" />
						<field name="direction" type="com.knapptech.autogen.shape.Vector3" />
					</class>
					<class name="LineSegment">
						<field name="startPoint" type="com.knapptech.autogen.shape.Vector3" />
						<field name="endPoint" type="com.knapptech.autogen.shape.Vector3" />
					</class>
					<class name="Triangle">
						<field name="startPoint" type="com.knapptech.autogen.shape.Vector3" />
						<field name="middlePoint" type="com.knapptech.autogen.shape.Vector3" />
						<field name="endPoint" type="com.knapptech.autogen.shape.Vector3" />
					</class>
					<class name="Mesh">
						<field name="vertices" type="java.util.List&lt;com.knapptech.autogen.shape.Vector3&gt;" />
					
					</class>
				</package>
				<package name="model" >
					<class name="Image">
						<field name="pixels" type="java.util.List&lt;com.knapptech.autogen.model.Color&gt;" />
						<field name="width" type="int" />
						<field name="height" type="int" />
					</class>
					<class name="Color">
						<field name="red" type="byte" />
						<field name="green" type="byte" />
						<field name="blue" type="byte" />
					</class>
				</package>
			</package>
		</package>
	</package>
</project>
