=== msknapp/JModelBuilder/src/main/resources/ModelDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://modelfactory.knapptech.com/ModelDefinition" 
xmlns:tns="http://modelfactory.knapptech.com/ModelDefinition" 
elementFormDefault="qualified">
	<element name="project" type="tns:project" />
	<complexType name="project">
		<sequence>
			<element name="defaults" type="tns:defaults" minOccurs="0" maxOccurs="1"/>
			<group ref="tns:pckg"/>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="package">
		<sequence>
			<group ref="tns:pckg"/>
		</sequence>
		<attribute name="name" type="string"/>
	</complexType>
	<complexType name="interface">
		<sequence>
			<element name="extends" type="tns:type" minOccurs="0" maxOccurs="unbounded"></element>
			<group ref="tns:fieldsandmethods"></group>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="enum">
		<sequence>
			<element name="implements" type="tns:type" minOccurs="0" maxOccurs="unbounded"/>
			<element name="enuminstance" type="tns:enuminstance" minOccurs="0" maxOccurs="unbounded" />
			<group ref="tns:fieldsandmethods"></group>
		</sequence>
		<attribute name="name" type="string"/>
		<attribute name="visibility" type="tns:visibility" default="public" use="optional"/>
	</complexType>
	<complexType name="enuminstance">
		<sequence>
			<element name="parameter" type="string" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string"/>
		<attribute name="initializer" type="string"/>
	</complexType>
	<complexType name="class">
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1" />
			<element name="genericparameter" type="tns:genericparameter" minOccurs="0" maxOccurs="unbounded" />
			<element name="implements" type="tns:type" minOccurs="0" maxOccurs="unbounded"/>
			<group ref="tns:fieldsandmethods"></group>
			<group ref="tns:c"/>
			<element name="extends" type="tns:type" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="strategy" type="tns:strategy" default="extensible" use="optional"/>
		<attribute name="abstract" type="boolean" default="false" use="optional"/>
		<attribute name="visibility" type="tns:visibility" default="public" use="optional"/>
	</complexType>
	<complexType name="genericparameter">
		<sequence>
			<element name="upperbounds" type="tns:type" minOccurs="0" maxOccurs="1" />
			<element name="lowerbounds" type="tns:type" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="representation" type="string" use="required"/>
	</complexType>
	<simpleType name="strategy">
		<restriction base="string">
			<enumeration value="bean"/><!-- just a java bean -->
			<enumeration value="immutable"/><!-- just an immutable java class -->
			<enumeration value="beanandinterface"/><!-- a bean version and its interface. -->
			<enumeration value="immutableandinterface"/><!-- an immutable version, and readonly interface -->
			<enumeration value="extensible"/><!-- both interfaces, a bean, and an immutable version -->
			<enumeration value="extensibleslave"/><!-- both interfaces, a bean, and an immutable version -->
			<enumeration value="singleton"/><!-- a singleton member -->
			<enumeration value="singletonandinterface"/><!-- a singleton member, and its interface. -->
			<enumeration value="managed"/><!-- make all interfaces, bean, immutable, and singleton members. -->
			<enumeration value="factory"/><!-- make all interfaces, bean, immutable, and singleton members. -->
			<enumeration value="locking"/><!-- make all interfaces, bean, immutable, and singleton members. -->
			<enumeration value="unlocking"/><!-- make all interfaces, bean, immutable, and singleton members. -->
		</restriction>
	</simpleType>
	<complexType name="requiredmethod">
		<all>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1" />
			<element name="returnType" type="tns:type" minOccurs="0"/>
			<element name="arguments" type="tns:arguments" minOccurs="0"/>
		</all>
		<attribute name="name" type="string" use="required"/>
		<attribute name="returnType" type="string" use="optional"/>
		<attribute name="visibility" type="tns:visibility" default="public"/>
		<attribute name="static" type="boolean" default="false"/>
		<attribute name="synchronized" type="boolean" default="false"/>
		<attribute name="abstract" type="boolean" default="false"/>
		<attribute name="overrides" type="boolean" default="false"/>
		<attribute name="final" type="boolean" default="false"/>
		<attribute name="modifiesClass" type="boolean" default="true"/>
	</complexType>
	<complexType name="field">
		<all>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1" />
			<element name="type" type="tns:type" minOccurs="0"/>
			<element name="initializer" type="string" minOccurs="0"/>
		</all>
		<attribute name="name" use="required" type="tns:fieldName"/>
		<attribute name="array" use="optional" type="boolean"/>
		<attribute name="type" use="optional" type="string"/>
		<attribute name="static" type="boolean" default="false"/>
		<attribute name="visibility" type="tns:visibility" default="private"/>
		<attribute name="gettable" type="boolean" default="true"/>
		<attribute name="settable" type="boolean" default="true"/>
		<attribute name="addable" type="boolean" default="true"/>
		<attribute name="removable" type="boolean" default="true"/>
		<attribute name="incrementable" type="boolean" default="true"/>
		<attribute name="decrementable" type="boolean" default="true"/>
		<attribute name="serializable" type="boolean" default="true"/>
		<attribute name="comparable" type="boolean" default="true"/>
		<attribute name="unique" type="boolean" default="true"/>
		<attribute name="synchronized" type="boolean" default="false"/>
		<attribute name="abstract" type="boolean" default="false"/>
		<attribute name="overrides" type="boolean" default="false"/>
		<attribute name="final" type="boolean" default="false"/>
		<attribute name="compareOrder" type="positiveInteger" default="99"/>
		<attribute name="key" type="boolean" default="false"/>
		<attribute name="nullable" type="boolean" default="true"/>
		<attribute name="immutable" type="boolean" default="false"/>
	</complexType>
	<complexType name="arguments">
		<sequence>
			<element name="argument" type="tns:argument" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="argument">
		<all>
			<element name="type" type="tns:type" minOccurs="0"/>
		</all>
		<attribute name="name" use="required" type="tns:fieldName"/>
		<attribute name="type" use="optional" type="string"/>
	</complexType>
	<complexType name="type">
		<sequence>
			<element name="type" type="string" minOccurs="0"/>
			<element name="generictype" type="tns:type" minOccurs="0" maxOccurs="unbounded"/>
			<element name="defaultImplementation" type="tns:type" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="type" type="string" use="optional" />
		<attribute name="arrayDimensions" type="int" default="0" use="optional"/>
	</complexType>
	
	
	<complexType name="defaults">
		<sequence>
			<element name="language" type="string" />
			<element name="mergeStrategy" type="tns:mergeStrategy" />
		</sequence>
	</complexType>
	<simpleType name="fieldName">
		<restriction base="string">
			<pattern value="([a-zA-Z0-9$_])*"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="visibility">
		<restriction base="string">
			<enumeration value="public"></enumeration>
			<enumeration value="protected"></enumeration>
			<enumeration value=""></enumeration>
			<enumeration value="package"></enumeration>
			<enumeration value="packageprivate"></enumeration>
			<enumeration value="private"></enumeration>
		</restriction>
	</simpleType>
	<group name="pckg" >
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1" />
			<element name="package" type="tns:package" minOccurs="0" maxOccurs="unbounded"/>
			<group ref="tns:c"></group>
		</sequence>
	</group>
	<group name="c">
		<sequence>
			<element name="interface" type="tns:interface"  minOccurs="0" maxOccurs="unbounded"/>
			<element name="enum" type="tns:enum"  minOccurs="0" maxOccurs="unbounded"/>
			<element name="class" type="tns:class"  minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</group>
	<simpleType name="mergeStrategy">
		<restriction base="string">
			<enumeration value="overwrite" />
			<enumeration value="merge" />
			<enumeration value="newonly" />
			<enumeration value="startnew" />
			<enumeration value="safe" />
			<enumeration value="stoponconflict" />
		</restriction>
	</simpleType>
	
	<group name="fieldsandmethods">
		<sequence>
			<element name="field" type="tns:field" minOccurs="0" maxOccurs="unbounded"/>
			<element name="requiredmethod" type="tns:requiredmethod" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</group>
</schema>

=== msknapp/JModelBuilder/src/main/resources/samples/Chess.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://modelfactory.knapptech.com/ModelDefinition"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://modelfactory.knapptech.com/ModelDefinition ../ModelDefinition.xsd" 
name="Chess">
	<defaults>
		<language>java</language>
		<mergeStrategy>merge</mergeStrategy>
	</defaults>
	<package name="com">
		<package name="knapptech">
			<package name="chess">
				<package name="pieces" >
					<class name="King" >
						<implements type="com.knapptech.chess.IPiece" />
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					<class name="Queen">
						<implements type="com.knapptech.chess.IPiece"/>
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					<class name="Bishop">
						<implements type="com.knapptech.chess.IPiece"/>
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					<class name="Knight">
						<implements type="com.knapptech.chess.IPiece"/>
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					<class name="Rook">
						<implements type="com.knapptech.chess.IPiece"/>
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					<class name="Pawn">
						<implements type="com.knapptech.chess.IPiece"/>
						<extends type="com.knapptech.chess.Piece"/>
					</class>
					
				</package>
				<package name="ai">
					<class name="Evaluator" strategy="extensible" >
						<requiredmethod name="evaluate" returnType="double">
							<arguments>
								<argument name="boardstatus">
									<type type="com.knapptech.chess.BoardStatus" />
								</argument>
							</arguments>
						</requiredmethod>
					</class>
					<class name="RecursiveEvaluator" strategy="factory">
						<implements type="com.knapptech.chess.ai.IEvaluator"/>
						<field name="evaluator" immutable="true" type="com.knapptech.chess.ai.IEvaluator"/>
						<field name="movesAhead" static="true" final="false" visibility="private" type="int"/>
						<requiredmethod name="getMoveConsiderations" returnType="com.knapptech.chess.ai.MoveConsideration"/>
					</class>
					<class name="MoveConsideration" >
						<field name="currentBoard" type="com.knapptech.chess.BoardStatus" />
						<field name="currentValue" type="double" />
						<field name="realValue" type="double"/>
						<field name="possibleMoves">
							<type>
								<type>java.util.HashMap</type>
								<generictype type="com.knapptech.chess.Move"/>
								<generictype type="com.knapptech.chess.ai.MoveConsideration"/>
							</type>
						</field>
					</class>
				</package>
				<enum name="ChessColor">
					<enuminstance name="WHITE" />
					<enuminstance name="BLACK" />
				</enum>
				<enum name="PieceType">
					<enuminstance name="KING" />
					<enuminstance name="QUEEN" />
					<enuminstance name="BISHOP" />
					<enuminstance name="KNIGHT" />
					<enuminstance name="ROOK" />
					<enuminstance name="PAWN" />
				</enum>
				<class name="PieceID" strategy="immutable" >
					<field name="type" type="com.knapptech.chess.PieceType" unique="true"/>
					<field name="color" type="com.knapptech.chess.ChessColor" unique="true" />
					<field name="startColumn" type="byte" unique="true" />
				</class>
				<class name="Piece" abstract="true" strategy="extensible">
					<comment>This is a piece in general, not considering any current state of a game.</comment>
					<field name="id" type="com.knapptech.chess.PieceID" />
					<requiredmethod name="getAttackableSquares" abstract="true">
						<returnType>
							<type>java.util.HashSet</type>
							<generictype type="com.knapptech.chess.Square"/>
						</returnType>
						<arguments>
							<argument name="position" type="com.knapptech.chess.Square"/>
						</arguments>
					</requiredmethod>
					<requiredmethod name="getReachableSquares" abstract="true">
						<returnType>
							<type>java.util.HashSet</type>
							<generictype type="com.knapptech.chess.Square"/>
						</returnType>
						<arguments>
							<argument name="position" type="com.knapptech.chess.Square"/>
						</arguments>
					</requiredmethod>
				</class>
				<class name="PieceStatus" strategy="immutable" >
					<comment>This describes the state of a piece considering its position on a board.</comment>
					<field name="boardStatus" type="com.knapptech.chess.BoardStatus"/>
					<field name="piece" type="com.knapptech.chess.Piece" />
					<field name="square" type="com.knapptech.chess.Square" />
					<requiredmethod name="getAttackableSquares" >
						<returnType>
							<type>java.util.HashSet</type>
							<generictype type="com.knapptech.chess.Square"/>
						</returnType>
						<arguments>
							<argument name="position" type="com.knapptech.chess.Square"/>
						</arguments>
					</requiredmethod>
					<requiredmethod name="getReachableSquares" >
						<returnType>
							<type>java.util.HashSet</type>
							<generictype type="com.knapptech.chess.Square"/>
						</returnType>
						<arguments>
							<argument name="position" type="com.knapptech.chess.Square"/>
						</arguments>
					</requiredmethod>
				</class>
				<class name="Board">
					<field name="rows">
						<type>
							<type>java.util.ArrayList</type>
							<generictype type="com.knapptech.chess.BoardRow"/>
						</type>
					</field>
				</class>
				<class name="BoardRow" strategy="managed" >
					<field name="number" type="int" key="true" />
					<field name="squares">
						<type>
							<type>java.util.ArrayList</type>
							<generictype type="com.knapptech.chess.Square"/>
						</type>
						<initializer>new ArrayList&lt;Square&gt;(10)</initializer>
					</field>
				</class>
				<class name="BoardColumn" strategy="managed" >
					<field name="number" type="int" key="true" />
					<field name="squares">
						<type>
							<type>java.util.ArrayList</type>
							<generictype type="com.knapptech.chess.Square"/>
						</type>
					</field>
				</class>
				<class name="SquareID" strategy="immutable">
					<field name="CAPTURED" type="com.knapptech.chess.SquareID" static="true" final="true" visibility="public" />
					<field name="row" type="int" key="true" />
					<field name="column" type="int" key="true" />
				</class>
				<class name="Square" strategy="managed">
					<field name="CAPTURED" type="com.knapptech.chess.Square" static="true" final="true" visibility="public" />
					<field name="id" type="com.knapptech.chess.SquareID" key="true" />
					<field name="color" type="com.knapptech.chess.ChessColor" settable="false"/>
					<requiredmethod name="getSquareName" returnType="java.lang.String"/>
					<requiredmethod name="getRow" returnType="int"/>
					<requiredmethod name="getColumn" returnType="int"/>
				</class>
				<class name="SquareStatus">
					<field name="square" type="com.knapptech.chess.Square" />
					<field name="occupant" type="com.knapptech.chess.Piece" />
					
				</class>
				<class name="Game">
					<field name="white" type="com.knapptech.chess.Player" />
					<field name="black" type="com.knapptech.chess.Player" />
					<field name="status" type="com.knapptech.chess.IBoardStatusReadable" />
					<requiredmethod name="move"/>
				</class>
				<class name="BoardStatus" strategy="extensible">
					<!-- Knows the position of all pieces, and whose turn it is. -->
					<field name="START" static="true" final="true" visibility="public"
						type="com.knapptech.chess.BoardStatus">
						<initializer>new BoardStatus()</initializer>
					</field>
					<field name="playersTurn" type="com.knapptech.chess.ChessColor" />
					<field name="piecePositions">
						<type>
							<type>java.util.HashMap</type>
							<generictype type="com.knapptech.chess.PieceID"/>
							<generictype type="com.knapptech.chess.PieceStatus"/>
						</type>
					</field>
					<field name="squaresStatus">
						<type>
							<type>java.util.HashMap</type>
							<generictype type="com.knapptech.chess.Square"/>
							<generictype type="com.knapptech.chess.SquareStatus"/>
						</type>
					</field>
					<requiredmethod name="getPossibleMoves">
						<returnType>
							<type>java.util.Set</type>
							<generictype type="com.knapptech.chess.Move"/>
						</returnType>
					</requiredmethod>
					<requiredmethod name="createFromMove" returnType="com.knapptech.chess.BoardStatus">
						<arguments>
							<argument name="move" type="com.knapptech.chess.Move"/>
						</arguments>
					</requiredmethod>
				</class>
				<class name="Player" strategy="managed">
					<field name="name" type="java.lang.String" key="true" />
					<field name="dateOfBirth" type="java.util.Calendar" />
					<field name="rank" type="int" />
				</class>
				<class name="Move">
					<field name="startSquare" type="com.knapptech.chess.Square" />
					<field name="endSquare" type="com.knapptech.chess.Square" />
					<field name="piece" type="com.knapptech.chess.Piece" />
				</class>
			</package>
		</package>
	</package>
</project>

=== msknapp/JModelBuilder/src/main/resources/samples/Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://modelfactory.knapptech.com/ModelDefinition"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://modelfactory.knapptech.com/ModelDefinition ModelDefinition.xsd" 
name="ExampleProject">
	<defaults>
		<language>java</language>
		<mergeStrategy>merge</mergeStrategy>
	</defaults>
	<package name="com">
		<package name="knapptech">
			<package name="example">
				<interface name="IPhysicalThing">
					<requiredmethod name="getLocation" returnType="java.lang.String"></requiredmethod>
				</interface>
				<interface name="IAnimal" >
					<extends>
						<type>com.knapptech.example.IPhysicalThing</type>
					</extends>
					<requiredmethod name="run" returnType="int"></requiredmethod>
				</interface>
				<class name="PhysicalThing" strategy="bean" abstract="true">
					<implements><type>com.knapptech.example.IPhysicalThing</type></implements>
					<requiredmethod name="fall" abstract="true"></requiredmethod>
				</class>
				<class name="Animal" strategy="bean" abstract="true">
					<implements><type>com.knapptech.example.IAnimal</type></implements>
					<field name="name" type="java.lang.String" nullable="false" />
					<requiredmethod name="move" abstract="true" ><returnType type="java.lang.String"/></requiredmethod>
					
					<requiredmethod name="mate" abstract="true" >
						<arguments>
							<argument name="other" type="com.knapptech.example.IPhysicalThing"/>
						</arguments>
					</requiredmethod>
					<extends><type>com.knapptech.example.PhysicalThing</type></extends>
				</class>
				<class name="Monkey" strategy="bean">
					<extends type="com.knapptech.example.Animal" />
				</class>
				<class name="Michael" strategy="singleton">
					<field name="firstname" type="java.lang.String"/>
					<field name="money" type="int" />
				</class>
			</package>
		</package>
	</package>
</project>

=== msknapp/JModelBuilder/target/classes/samples/World.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://modelfactory.knapptech.com/ModelDefinition"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://modelfactory.knapptech.com/ModelDefinition ModelDefinition.xsd" 
name="StockMarket">
	<defaults>
		<language>java</language>
		<mergeStrategy>merge</mergeStrategy>
	</defaults>
	<package name="com">
		<package name="knapptech">
			<package name="world">
				<class name="LandMass" strategy="extensible">
					<field name="countries">
						<type type="java.util.List">
							<generictype>com.knapptech.world.ICountry</generictype>
						</type>
					</field>
				</class>
				<class name="Country" strategy="extensible">
					
				</class>
				<class name="Continent">
					<extends>com.knapptech.world.AbstractLandMass</extends>
					<implements>com.knapptech.world.LandMass</implements>
					
				</class>
				<class name="Ocean" strategy="extensible">
					
				
				</class>
				
			</package>
		</package>
	</package>
</project>

=== msknapp/JModelBuilder/src/main/resources/samples/Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://modelfactory.knapptech.com/ModelDefinition"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://modelfactory.knapptech.com/ModelDefinition ../ModelDefinition.xsd" 
name="MyApplication">
	<defaults>
		<language>java</language>
		<mergeStrategy>merge</mergeStrategy>
	</defaults>
	<package name="com">
		<package name="mycompanyname">
			<package name="myapplicationname">
				<interface name="MyInterface">
					<requiredmethod name="interfacesRequiredMethod"/>
				</interface>
				<enum name="MyEnum">
					
				</enum>
				<class name="MyClass" strategy="bean">
					<field name="myField" type="int" />
					<requiredmethod name="myRequiredMethod" />
				</class>
			</package>
		</package>
	</package>
</project>

=== msknapp/JModelBuilder/src/main/resources/samples/StockMarket.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://modelfactory.knapptech.com/ModelDefinition"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://modelfactory.knapptech.com/ModelDefinition ModelDefinition.xsd" 
name="StockMarket">
	<defaults>
		<language>java</language>
		<mergeStrategy>merge</mergeStrategy>
	</defaults>
	<package name="com">
		<package name="knapptech" >
			<package name="stockmarket">
				<interface name="ITradeable">
					<requiredmethod name="getPrice" returnType="double">
						<arguments>
							<argument name="date" type="java.util.Calendar" />
						</arguments>
					</requiredmethod>
				</interface>
				<class name="Company" strategy="extensible">
					<implements type="com.knapptech.stockmarket.ITradeable"/>
					<field name="ticker" type="java.lang.String" nullable="false" immutable="true" compareOrder="1"/>
					<field name="priceHistory" type="com.knapptech.stockmarket.PriceHistory"/>
				</class>
				<class name="PriceHistory" strategy="singleton">
					<field name="ticker" type="java.lang.String" nullable="false" immutable="true" compareOrder="1"/>
					<field name="prices">
						<type>
							<type>java.util.List</type>
							<generictype type="com.knapptech.stockmarket.PriceRecord"/>
						</type>
					</field>
				</class>
				<class name="PriceRecord" strategy="immutable">
					<field name="date" type="java.util.Calendar" nullable="false" compareOrder="1" />
					<field name="price" type="java.lang.Double" nullable="false" />
				</class>
				<class name="CarFactory" strategy="managed">
					<field name="model" type="java.lang.String" immutable="true" key="true" compareOrder="1"/>
					<field name="year" type="int" immutable="true" compareOrder="2"/>
				</class>
			</package>
			<package name="math">
				<class name="Pair" strategy="bean">
					<genericparameter representation="E"></genericparameter>
					<field name="first" type="com.knapptech.math.Pair.E"/>
					<field name="second" type="com.knapptech.math.Pair.E"/>
				</class>
				<class name="MyArray">
					<field name="thearray" type="int" array="true" />
				</class>
			</package>
		</package>
	</package>
</project>
